/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmbulanceRouteImport } from './routes/ambulance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterVolunteerRouteImport } from './routes/register/volunteer'
import { Route as RegisterTrafficRouteImport } from './routes/register/traffic'
import { Route as RegisterHospitalRouteImport } from './routes/register/hospital'
import { Route as RegisterCommandRouteImport } from './routes/register/command'
import { Route as RegisterCitizenRouteImport } from './routes/register/citizen'
import { Route as RegisterAmbulanceRouteImport } from './routes/register/ambulance'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceRoute = AmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVolunteerRoute = RegisterVolunteerRouteImport.update({
  id: '/register/volunteer',
  path: '/register/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTrafficRoute = RegisterTrafficRouteImport.update({
  id: '/register/traffic',
  path: '/register/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterHospitalRoute = RegisterHospitalRouteImport.update({
  id: '/register/hospital',
  path: '/register/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCommandRoute = RegisterCommandRouteImport.update({
  id: '/register/command',
  path: '/register/command',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCitizenRoute = RegisterCitizenRouteImport.update({
  id: '/register/citizen',
  path: '/register/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAmbulanceRoute = RegisterAmbulanceRouteImport.update({
  id: '/register/ambulance',
  path: '/register/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analytics': typeof AnalyticsRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/tracking': typeof TrackingRoute
  '/traffic': typeof TrafficRoute
  '/volunteer': typeof VolunteerRoute
  '/register/ambulance': typeof RegisterAmbulanceRoute
  '/register/citizen': typeof RegisterCitizenRoute
  '/register/command': typeof RegisterCommandRoute
  '/register/hospital': typeof RegisterHospitalRoute
  '/register/traffic': typeof RegisterTrafficRoute
  '/register/volunteer': typeof RegisterVolunteerRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analytics': typeof AnalyticsRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/tracking': typeof TrackingRoute
  '/traffic': typeof TrafficRoute
  '/volunteer': typeof VolunteerRoute
  '/register/ambulance': typeof RegisterAmbulanceRoute
  '/register/citizen': typeof RegisterCitizenRoute
  '/register/command': typeof RegisterCommandRoute
  '/register/hospital': typeof RegisterHospitalRoute
  '/register/traffic': typeof RegisterTrafficRoute
  '/register/volunteer': typeof RegisterVolunteerRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analytics': typeof AnalyticsRoute
  '/citizen': typeof CitizenRoute
  '/command': typeof CommandRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hospital': typeof HospitalRoute
  '/login': typeof LoginRoute
  '/tracking': typeof TrackingRoute
  '/traffic': typeof TrafficRoute
  '/volunteer': typeof VolunteerRoute
  '/register/ambulance': typeof RegisterAmbulanceRoute
  '/register/citizen': typeof RegisterCitizenRoute
  '/register/command': typeof RegisterCommandRoute
  '/register/hospital': typeof RegisterHospitalRoute
  '/register/traffic': typeof RegisterTrafficRoute
  '/register/volunteer': typeof RegisterVolunteerRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambulance'
    | '/analytics'
    | '/citizen'
    | '/command'
    | '/forgot-password'
    | '/hospital'
    | '/login'
    | '/tracking'
    | '/traffic'
    | '/volunteer'
    | '/register/ambulance'
    | '/register/citizen'
    | '/register/command'
    | '/register/hospital'
    | '/register/traffic'
    | '/register/volunteer'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambulance'
    | '/analytics'
    | '/citizen'
    | '/command'
    | '/forgot-password'
    | '/hospital'
    | '/login'
    | '/tracking'
    | '/traffic'
    | '/volunteer'
    | '/register/ambulance'
    | '/register/citizen'
    | '/register/command'
    | '/register/hospital'
    | '/register/traffic'
    | '/register/volunteer'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/ambulance'
    | '/analytics'
    | '/citizen'
    | '/command'
    | '/forgot-password'
    | '/hospital'
    | '/login'
    | '/tracking'
    | '/traffic'
    | '/volunteer'
    | '/register/ambulance'
    | '/register/citizen'
    | '/register/command'
    | '/register/hospital'
    | '/register/traffic'
    | '/register/volunteer'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbulanceRoute: typeof AmbulanceRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CitizenRoute: typeof CitizenRoute
  CommandRoute: typeof CommandRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HospitalRoute: typeof HospitalRoute
  LoginRoute: typeof LoginRoute
  TrackingRoute: typeof TrackingRoute
  TrafficRoute: typeof TrafficRoute
  VolunteerRoute: typeof VolunteerRoute
  RegisterAmbulanceRoute: typeof RegisterAmbulanceRoute
  RegisterCitizenRoute: typeof RegisterCitizenRoute
  RegisterCommandRoute: typeof RegisterCommandRoute
  RegisterHospitalRoute: typeof RegisterHospitalRoute
  RegisterTrafficRoute: typeof RegisterTrafficRoute
  RegisterVolunteerRoute: typeof RegisterVolunteerRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance': {
      id: '/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/volunteer': {
      id: '/register/volunteer'
      path: '/register/volunteer'
      fullPath: '/register/volunteer'
      preLoaderRoute: typeof RegisterVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/traffic': {
      id: '/register/traffic'
      path: '/register/traffic'
      fullPath: '/register/traffic'
      preLoaderRoute: typeof RegisterTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/hospital': {
      id: '/register/hospital'
      path: '/register/hospital'
      fullPath: '/register/hospital'
      preLoaderRoute: typeof RegisterHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/command': {
      id: '/register/command'
      path: '/register/command'
      fullPath: '/register/command'
      preLoaderRoute: typeof RegisterCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/citizen': {
      id: '/register/citizen'
      path: '/register/citizen'
      fullPath: '/register/citizen'
      preLoaderRoute: typeof RegisterCitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/ambulance': {
      id: '/register/ambulance'
      path: '/register/ambulance'
      fullPath: '/register/ambulance'
      preLoaderRoute: typeof RegisterAmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbulanceRoute: AmbulanceRoute,
  AnalyticsRoute: AnalyticsRoute,
  CitizenRoute: CitizenRoute,
  CommandRoute: CommandRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HospitalRoute: HospitalRoute,
  LoginRoute: LoginRoute,
  TrackingRoute: TrackingRoute,
  TrafficRoute: TrafficRoute,
  VolunteerRoute: VolunteerRoute,
  RegisterAmbulanceRoute: RegisterAmbulanceRoute,
  RegisterCitizenRoute: RegisterCitizenRoute,
  RegisterCommandRoute: RegisterCommandRoute,
  RegisterHospitalRoute: RegisterHospitalRoute,
  RegisterTrafficRoute: RegisterTrafficRoute,
  RegisterVolunteerRoute: RegisterVolunteerRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
